name: .NET Core

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT : true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.300'
    - name: Publish
      run: dotnet publish -c Release -r win-x64 -P:PublishSingleFile=true  --self-contained false H2CodezPatcher
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: H2CodezPatcher
        path: H2CodezPatcher\bin\Release\net5.0\win-x64\publish\

  release:
    if: |
      github.event.action != 'pull_request' &&
      github.ref == 'refs/heads/main' &&
      github.repository == 'Project-Cartographer/H2Codez-Installer/'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v2
      with:
        name: H2CodezPatcher
        path: patcher_win64
    - uses: ncipollo/release-action@v1
      with:
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: patcher_win64/*
        tag: ${{ github.run_id }}